FROM --platform=linux/amd64 justb4/jmeter:latest

USER root

# Install Prometheus Backend Listener plugin
COPY jmeter-prometheus-plugin.jar /opt/apache-jmeter-5.5/lib/ext/jmeter-prometheus-plugin.jar

